# Generated by Django 6.0.4 on 2026-05-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0003_plano_generacion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='co2_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='es_alternativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plano',
            name='plano_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativas', to='planos.plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='puntuacion_sostenibilidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plano',
            name='tiempo_estimado_dias',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
