# Generated by Django on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='num_pisos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de pisos de la construcción'),
        ),
    ]