# Generated by Django 6.0.4 on 2026-04-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_scraping_cache_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='preciomaterialscrapeado',
            new_name='materiales__nombre__3e1dfa_idx',
            old_name='materiales_p_nombre__5cb722_idx',
        ),
        migrations.RenameIndex(
            model_name='preciomaterialscrapeado',
            new_name='materiales__fuente_976178_idx',
            old_name='materiales_p_fuente_9f99c7_idx',
        ),
    ]
